import './globals.css'
import { Inter } from 'next/font/google'
import { bebas_neue } from '@/utils/fonts'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={bebas_neue.className}>{children}</body>
    </html>
  )
}
